import splashFaces from "./splash-faces.json";

/**
 * Owner face picker (M2-06C) logic: the unit forms to mark, the `face_points` row shape, and the
 * JSON export. Points are recorded in web-splash pixels
 * (`public/assets/units/<unit>/illustration-<form>.png`, 1024×1024) and exported in master splash
 * pixels (`art/legacy/units/<unit>/splash/<form>.png`), the space of `art/legacy/ui/ui.json`'s cards.
 * `splash-faces.json` is generated by `art/legacy/tools/bfr_faces.py`.
 */

export type Point = readonly [x: number, y: number];

export const MARKERS = ["leftEye", "rightEye", "chin"] as const;
export type Marker = (typeof MARKERS)[number];

export type FacePoints = Readonly<Record<Marker, Point>>;

export const MARKER_LABELS: Readonly<Record<Marker, string>> = {
  leftEye: "Left eye (image left)",
  rightEye: "Right eye (image right)",
  chin: "Chin",
};

export const FORMS = ["3star", "4star", "5star", "6star", "7star", "omni"] as const;
export type Form = (typeof FORMS)[number];

export const FORM_LABELS: Readonly<Record<Form, string>> = {
  "3star": "3★",
  "4star": "4★",
  "5star": "5★",
  "6star": "6★",
  "7star": "7★",
  omni: "Omni",
};

/** How a web splash maps onto its master: master = (web − offset) / scale + origin. */
export type SplashFrame = {
  masterSize: readonly [number, number];
  origin: readonly [number, number];
  scale: number;
  offset: readonly [number, number];
};

export type SplashForm = {
  unit: string;
  form: Form;
  /** Web path of the splash the owner marks. */
  src: string;
  frame: SplashFrame;
  /** Anime face cascade guess, or null when the cascade found no face. */
  guess: FacePoints | null;
};

export const SPLASH_SIZE: number = splashFaces.size;

function isForm(value: string): value is Form {
  return (FORMS as readonly string[]).includes(value);
}

function toPoint(value: readonly number[]): Point {
  return [value[0] ?? 0, value[1] ?? 0];
}

type RawEntry = {
  frame: { masterSize: number[]; origin: number[]; scale: number; offset: number[] };
  guess: Record<Marker, number[]> | null;
};

/** Every locked splash form, in unit then tier order. */
export const SPLASH_FORMS: readonly SplashForm[] = Object.entries(
  splashFaces.units as Record<string, Record<string, RawEntry>>,
).flatMap(([unit, forms]) =>
  FORMS.filter((form) => forms[form]).map((form): SplashForm => {
    const entry = forms[form] as RawEntry;
    return {
      unit,
      form,
      src: `/assets/units/${unit}/illustration-${form}.png`,
      frame: {
        masterSize: toPoint(entry.frame.masterSize),
        origin: toPoint(entry.frame.origin),
        scale: entry.frame.scale,
        offset: toPoint(entry.frame.offset),
      },
      guess: entry.guess
        ? {
            leftEye: toPoint(entry.guess.leftEye),
            rightEye: toPoint(entry.guess.rightEye),
            chin: toPoint(entry.guess.chin),
          }
        : null,
    };
  }),
);

export function formKey(unit: string, form: string): string {
  return `${unit}/${form}`;
}

/** A `face_points` row. */
export type FacePointsRow = {
  unit_id: string;
  form: string;
  left_eye_x: number;
  left_eye_y: number;
  right_eye_x: number;
  right_eye_y: number;
  chin_x: number;
  chin_y: number;
};

export const FACE_POINTS_COLUMNS =
  "unit_id, form, left_eye_x, left_eye_y, right_eye_x, right_eye_y, chin_x, chin_y";

export function pointsFromRow(row: FacePointsRow): FacePoints {
  return {
    leftEye: [row.left_eye_x, row.left_eye_y],
    rightEye: [row.right_eye_x, row.right_eye_y],
    chin: [row.chin_x, row.chin_y],
  };
}

export function rowFromPoints(unit: string, form: Form, points: FacePoints): FacePointsRow {
  return {
    unit_id: unit,
    form,
    left_eye_x: points.leftEye[0],
    left_eye_y: points.leftEye[1],
    right_eye_x: points.rightEye[0],
    right_eye_y: points.rightEye[1],
    chin_x: points.chin[0],
    chin_y: points.chin[1],
  };
}

/** Saved rows keyed by `formKey`; rows for unknown forms are dropped. */
export function savedByKey(rows: readonly FacePointsRow[]): Record<string, FacePoints> {
  const known = new Set(SPLASH_FORMS.map((f) => formKey(f.unit, f.form)));
  const out: Record<string, FacePoints> = {};
  for (const row of rows) {
    const key = formKey(row.unit_id, row.form);
    if (known.has(key)) out[key] = pointsFromRow(row);
  }
  return out;
}

function validPoint(value: unknown): value is Point {
  return (
    Array.isArray(value) &&
    value.length === 2 &&
    value.every((n) => typeof n === "number" && Number.isFinite(n) && n >= 0 && n <= SPLASH_SIZE)
  );
}

/** The save request's form and points, or null when they are not a known form with 3 in-range points. */
export function parseSave(
  unit: unknown,
  form: unknown,
  points: unknown,
): { unit: string; form: Form; points: FacePoints } | null {
  if (typeof unit !== "string" || typeof form !== "string" || !isForm(form)) return null;
  if (!SPLASH_FORMS.some((f) => f.unit === unit && f.form === form)) return null;
  if (typeof points !== "object" || points === null) return null;
  const p = points as Record<string, unknown>;
  if (!MARKERS.every((m) => validPoint(p[m]))) return null;
  const round = (pt: Point): Point => [Math.round(pt[0] * 10) / 10, Math.round(pt[1] * 10) / 10];
  return {
    unit,
    form,
    points: {
      leftEye: round(p.leftEye as Point),
      rightEye: round(p.rightEye as Point),
      chin: round(p.chin as Point),
    },
  };
}

/** A web-splash point in master splash pixels, rounded to whole pixels. */
export function webToMaster(frame: SplashFrame, point: Point): Point {
  return [
    Math.round((point[0] - frame.offset[0]) / frame.scale + frame.origin[0]),
    Math.round((point[1] - frame.offset[1]) / frame.scale + frame.origin[1]),
  ];
}

/** The download: `cards.units.<unit>.faces.<form>` like art/legacy/ui/ui.json's `cards.units.<unit>`. */
export type FaceExport = {
  cards: {
    faceNote: string;
    units: Record<string, { faces: Partial<Record<Form, FacePoints>> }>;
  };
};

export const FACE_EXPORT_NOTE =
  "Face points from the owner face picker: leftEye (the eye on the image's left), rightEye, and " +
  "chin as [x, y] in master splash pixels (art/legacy/units/<unit>/splash/<form>.png). Merge " +
  "cards.units.<unit>.faces into art/legacy/ui/ui.json.";

export function buildExport(saved: Readonly<Record<string, FacePoints>>): FaceExport {
  const units: FaceExport["cards"]["units"] = {};
  for (const splash of SPLASH_FORMS) {
    const points = saved[formKey(splash.unit, splash.form)];
    if (!points) continue;
    const unit = units[splash.unit] ?? { faces: {} };
    unit.faces[splash.form] = {
      leftEye: webToMaster(splash.frame, points.leftEye),
      rightEye: webToMaster(splash.frame, points.rightEye),
      chin: webToMaster(splash.frame, points.chin),
    };
    units[splash.unit] = unit;
  }
  return { cards: { faceNote: FACE_EXPORT_NOTE, units } };
}
