// Content seeding: turns packages/data/content/ into supabase/seed.sql and the CONTENT_VERSION
// constant, so Postgres server functions and the client read the same content version (M3-02).
import { createHash } from "node:crypto";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { type Unit, UnitSchema } from "../src/schemas/unit.ts";
import {
  validateBannerFile,
  validateEnemyFile,
  validateEvolutionRefs,
  validateGuestFile,
  validateItemFile,
  validateSphereFile,
  validateStageFile,
  validateUnitFile,
} from "../src/validate.ts";

export const contentDir = join(import.meta.dirname, "..", "content");
export const seedSqlPath = join(import.meta.dirname, "..", "..", "..", "supabase", "seed.sql");
export const versionModulePath = join(import.meta.dirname, "..", "src", "content-version.ts");

export type ContentKind = "unit" | "item" | "enemy" | "stage" | "banner" | "guest" | "sphere";

export interface ContentItem {
  kind: ContentKind;
  id: string;
  data: unknown;
}

const kindDirs: readonly [ContentKind, string][] = [
  ["unit", "units"],
  ["item", "items"],
  ["enemy", "enemies"],
  ["stage", "stages"],
  ["banner", "banners"],
  ["guest", "guests"],
  ["sphere", "spheres"],
];

const DOLLAR_TAG = "$bfr_content$";

/** Drops a unit's `source` provenance: it never reaches the database or players (IP_POLICY). */
function withoutProvenance(data: unknown): unknown {
  if (typeof data !== "object" || data === null || !("source" in data)) return data;
  const { source: _source, ...rest } = data as Record<string, unknown>;
  return rest;
}

/** Reads and validates every content file; throws listing every validation error. */
export function loadContent(dir = contentDir): ContentItem[] {
  const items: ContentItem[] = [];
  const errors: string[] = [];
  const enemyIds = new Set<string>();
  const unitForms = new Map<string, Set<string>>();
  const units: Unit[] = [];
  const itemIds = new Set<string>();
  for (const [kind, sub] of kindDirs) {
    const names = readdirSync(join(dir, sub))
      .filter((name) => name.endsWith(".json"))
      .sort();
    for (const name of names) {
      const file = `${sub}/${name}`;
      const id = name.slice(0, -".json".length);
      const data: unknown = JSON.parse(readFileSync(join(dir, file), "utf8"));
      if (kind === "unit") {
        const unitErrors = validateUnitFile(file, data);
        errors.push(...unitErrors);
        if (unitErrors.length === 0) {
          const unit = UnitSchema.parse(data);
          unitForms.set(id, new Set(unit.forms.map((form) => form.id)));
          units.push(unit);
        }
      }
      if (kind === "item") {
        errors.push(...validateItemFile(file, data));
        itemIds.add(id);
      }
      if (kind === "enemy") {
        errors.push(...validateEnemyFile(file, data));
        enemyIds.add(id);
      }
      if (kind === "stage") errors.push(...validateStageFile(file, data, enemyIds));
      if (kind === "banner") errors.push(...validateBannerFile(file, data, unitForms));
      if (kind === "guest")
        errors.push(...validateGuestFile(file, data, new Set(unitForms.keys())));
      if (kind === "sphere")
        errors.push(...validateSphereFile(file, data, new Set(unitForms.keys())));
      items.push({ kind, id, data: withoutProvenance(data) });
    }
  }
  const unitIds = new Set(unitForms.keys());
  for (const unit of units) {
    errors.push(...validateEvolutionRefs(`units/${unit.id}.json`, unit, unitIds, itemIds));
  }
  if (errors.length > 0) throw new Error(`content is invalid:\n${errors.join("\n")}`);
  return items;
}

/** A 16-hex-digit hash of the content: kind, id, and compact JSON of every item, in order. */
export function contentVersion(items: readonly ContentItem[]): string {
  const hash = createHash("sha256");
  for (const item of items) hash.update(`${item.kind}/${item.id}\t${JSON.stringify(item.data)}\n`);
  return hash.digest("hex").slice(0, 16);
}

/** Renders supabase/seed.sql: one idempotent seed_content() call carrying every item. */
export function renderSeedSql(items: readonly ContentItem[], version: string): string {
  const rows = items.map((item) => JSON.stringify(item));
  const payload = `[\n${rows.join(",\n")}\n]`;
  if (payload.includes(DOLLAR_TAG)) throw new Error(`content contains ${DOLLAR_TAG}`);
  return [
    "-- GENERATED by `pnpm --filter @bfr/data seed` from packages/data/content/. Do not edit.",
    "-- Idempotent: loads exactly this content into public.content_items and content_version.",
    `select public.seed_content('${version}', ${DOLLAR_TAG}${payload}${DOLLAR_TAG}::jsonb);`,
    "",
  ].join("\n");
}

/** Renders packages/data/src/content-version.ts. */
export function renderVersionModule(version: string): string {
  return [
    "// GENERATED by `pnpm --filter @bfr/data seed` from content/. Do not edit.",
    "/** Hash of every content file; equals public.content_version.version once seeded. */",
    `export const CONTENT_VERSION = "${version}";`,
    "",
  ].join("\n");
}
