// GENERATED by `pnpm --filter @bfr/data seed` from content/. Do not edit.
/** Hash of every content file; equals public.content_version.version once seeded. */
export const CONTENT_VERSION = "dd03199bfb97dfa1";
