// Generated by art/tools/bfr_ui.py from art/maps/maps.json (M6-07S). Do not edit by hand.

export type RegionArea = {
  id: string;
  /** The story chapter played as this area, or null for a planned area. */
  chapter: number | null;
  /** The landmark where the area plate sits, as fractions of the map's width and height. */
  anchor: { x: number; y: number };
};

export type RegionMap = {
  id: string;
  name: string;
  src: string;
  width: number;
  height: number;
  areas: readonly RegionArea[];
};

export const REGION_MAPS: readonly RegionMap[] = [
  {
    id: "brightmere-vale",
    name: "Brightmere Vale",
    src: "/assets/maps/brightmere-vale.webp",
    width: 1024,
    height: 1536,
    areas: [
      { id: "ember-road", chapter: 1, anchor: { x: 0.625, y: 0.7422 } },
      { id: "saltglass-coast", chapter: 2, anchor: { x: 0.9053, y: 0.5469 } },
      { id: "planned-fire", chapter: null, anchor: { x: 0.1611, y: 0.6055 } },
      { id: "planned-earth", chapter: null, anchor: { x: 0.5059, y: 0.459 } },
      { id: "planned-thunder", chapter: null, anchor: { x: 0.8203, y: 0.3125 } },
      { id: "planned-light", chapter: null, anchor: { x: 0.2129, y: 0.3372 } },
      { id: "planned-dark", chapter: null, anchor: { x: 0.2344, y: 0.1172 } },
      { id: "planned-spire", chapter: null, anchor: { x: 0.6299, y: 0.0586 } },
    ],
  },
];
