// Generated by art/tools/bfr_ui.py export; do not edit by hand.

/** Pixel size of each exported UI piece in public/assets/ui/<name>.webp (2x logical). */
export const UI_ASSETS = {
  "title-keyart": { width: 1024, height: 1536 },
  "nav-home": { width: 180, height: 157 },
  "nav-unit": { width: 180, height: 172 },
  "nav-squad": { width: 180, height: 176 },
  "nav-items": { width: 180, height: 160 },
  "nav-summon": { width: 180, height: 203 },
  "nav-other": { width: 180, height: 155 },
  "nav-tile": { width: 208, height: 241 },
  "nav-tile-selected": { width: 208, height: 235 },
  "nav-base": { width: 1280, height: 264 },
  "top-bar": { width: 1280, height: 218 },
  "top-crest": { width: 380, height: 206 },
  "icon-gem": { width: 96, height: 97 },
  "icon-zel": { width: 96, height: 95 },
  "card-frame": { width: 250, height: 727 },
  "card-leader": { width: 84, height: 84 },
  "orb-fire": { width: 88, height: 88 },
  "orb-water": { width: 88, height: 88 },
  "orb-thunder": { width: 88, height: 88 },
  "orb-earth": { width: 88, height: 88 },
  "orb-light": { width: 88, height: 87 },
  "orb-dark": { width: 88, height: 87 },
  "util-strip": { width: 1280, height: 135 },
  "util-tab": { width: 232, height: 99 },
  "util-book": { width: 128, height: 66 },
  "util-castle": { width: 128, height: 105 },
  "util-scroll": { width: 128, height: 100 },
  "util-chest": { width: 128, height: 97 },
  "util-flourish": { width: 240, height: 102 },
  "mode-quest": { width: 680, height: 441 },
  "mode-trials": { width: 520, height: 464 },
  "mode-dungeons": { width: 520, height: 440 },
  "mode-backdrop": { width: 1280, height: 853 },
  "dot-on": { width: 32, height: 32 },
  "dot-off": { width: 32, height: 32 },
  ticker: { width: 1280, height: 94 },
  "bg-slate": { width: 512, height: 512 },
  "battle-top": { width: 1280, height: 117 },
  "btn-pill": { width: 300, height: 63 },
  "btn-pill-lit": { width: 300, height: 65 },
  "btn-hub": { width: 520, height: 237 },
  "boss-band": { width: 1280, height: 138 },
  "boss-crest": { width: 240, height: 132 },
  "boss-hp-frame": { width: 1280, height: 67 },
  "od-frame": { width: 1280, height: 67 },
  "unit-card": { width: 624, height: 186 },
  "unit-card-empty": { width: 624, height: 174 },
  "badge-leader": { width: 64, height: 40 },
  "item-panel": { width: 1280, height: 318 },
  "item-slot": { width: 232, height: 248 },
  "fill-hp": { width: 600, height: 50 },
  "fill-bb": { width: 600, height: 50 },
  "fill-sbb": { width: 600, height: 50 },
  "fill-ubb": { width: 600, height: 50 },
  "fill-boss": { width: 1240, height: 74 },
  "fill-od": { width: 1240, height: 103 },
  "crystal-bc": { width: 48, height: 70 },
  "crystal-hc": { width: 48, height: 71 },
  "fx-hit": { width: 192, height: 193 },
  "fx-spark": { width: 256, height: 254 },
  "fx-crit": { width: 256, height: 256 },
  "target-reticle": { width: 192, height: 189 },
  "icon-weak": { width: 64, height: 72 },
  "icon-resist": { width: 64, height: 68 },
  "icon-guard": { width: 80, height: 95 },
  "status-poison": { width: 64, height: 64 },
  "status-weak": { width: 64, height: 64 },
  "status-sick": { width: 64, height: 64 },
  "status-injury": { width: 64, height: 64 },
  "status-curse": { width: 64, height: 64 },
  "status-paralysis": { width: 64, height: 64 },
  "buff-atk": { width: 64, height: 64 },
  "buff-def": { width: 64, height: 64 },
  "buff-rec": { width: 64, height: 64 },
  "buff-crit": { width: 64, height: 64 },
  "buff-spark": { width: 64, height: 64 },
  "buff-bb-atk": { width: 64, height: 64 },
  "buff-element": { width: 64, height: 64 },
  "buff-regen": { width: 64, height: 64 },
  "buff-mitigation": { width: 64, height: 64 },
  "buff-elem-guard": { width: 64, height: 64 },
  "buff-barrier": { width: 64, height: 64 },
  "buff-last-stand": { width: 64, height: 64 },
  "buff-gauge-fill": { width: 64, height: 64 },
  "buff-gauge-rate": { width: 64, height: 64 },
  "buff-drop-rate": { width: 64, height: 64 },
  "debuff-atk": { width: 64, height: 64 },
  "debuff-def": { width: 64, height: 64 },
  "debuff-spark-vuln": { width: 64, height: 64 },
  "debuff-dot": { width: 64, height: 64 },
  "banner-wave": { width: 1280, height: 254 },
  "banner-boss": { width: 1280, height: 284 },
  "cutin-ribbon-bb": { width: 1140, height: 332 },
  "cutin-ribbon-sbb": { width: 1140, height: 335 },
  "cutin-ribbon-ubb": { width: 1140, height: 332 },
  "cutin-streaks": { width: 1280, height: 853 },
  "unit-frame-fire": { width: 240, height: 241 },
  "unit-frame-water": { width: 240, height: 234 },
  "unit-frame-thunder": { width: 240, height: 235 },
  "unit-frame-earth": { width: 240, height: 238 },
  "unit-frame-light": { width: 240, height: 235 },
  "unit-frame-dark": { width: 240, height: 237 },
  "bg-olive": { width: 512, height: 512 },
  "title-plate": { width: 640, height: 111 },
  "squad-pedestal": { width: 340, height: 114 },
  "stat-plate": { width: 440, height: 92 },
  "squad-arrow": { width: 112, height: 119 },
  "leader-ribbon": { width: 260, height: 79 },
  "skill-tag-red": { width: 340, height: 70 },
  "skill-tag-violet": { width: 340, height: 59 },
  "skill-tag-blue": { width: 340, height: 59 },
} as const;

export type UiAsset = keyof typeof UI_ASSETS;

/**
 * The measured inner face of each text-bearing piece (ui.json `textBox`), in its export's own
 * 2x pixels: app text is fitted inside this box, never placed by eye (ART_GUIDE.md → Text on
 * UI pieces).
 */
export const UI_TEXT_BOXES = {
  "btn-hub": { x: 36, y: 26, width: 448, height: 185 },
  "boss-band": { x: 224, y: 68, width: 596, height: 62 },
  "cutin-ribbon-bb": { x: 92, y: 112, width: 688, height: 100 },
  "cutin-ribbon-sbb": { x: 92, y: 112, width: 688, height: 100 },
  "cutin-ribbon-ubb": { x: 92, y: 112, width: 688, height: 100 },
  "title-plate": { x: 22, y: 14, width: 562, height: 82 },
  "stat-plate": { x: 12, y: 10, width: 416, height: 72 },
  "leader-ribbon": { x: 30, y: 12, width: 200, height: 52 },
  "skill-tag-red": { x: 14, y: 8, width: 288, height: 50 },
  "skill-tag-violet": { x: 14, y: 7, width: 288, height: 42 },
  "skill-tag-blue": { x: 14, y: 7, width: 288, height: 42 },
} as const satisfies Partial<
  Record<UiAsset, { x: number; y: number; width: number; height: number }>
>;

export type UiTextPiece = keyof typeof UI_TEXT_BOXES;

/** Pixel size of every showcase card in public/assets/ui/cards/<unit>-<form>.webp. */
export const CARD_ART_SIZE = { width: 250, height: 690 } as const;

/**
 * Battle portraits in public/assets/ui/cards/battle/<unit>-<form>.webp: pixel size, and the
 * top-left offset inside the 2x unit-card export that covers its portrait window.
 */
export const PORTRAIT_ART = { width: 220, height: 166, x: 12, y: 10 } as const;

/** Pixel size of every burst cut-in portrait in public/assets/ui/cards/cutin/<unit>-<form>.webp. */
export const CUTIN_ART_SIZE = { width: 1280, height: 1040 } as const;

/** Pixel size of every unit thumbnail icon in public/assets/ui/cards/thumb/<unit>-<form>.webp. */
export const THUMB_ART_SIZE = { width: 256, height: 256 } as const;
